blank_issues_enabled: true
contact_links:
  - name: ⚡ Feature Request
    url: https://github.com/Chrede88/qubt/discussions
    about: Please use GitHub Discussions for feature requests
  - name: 🙋 Question
    url: https://github.com/Chrede88/qubt/discussions
    about: Please use GitHub Discussions for questions about the theme
